"""Build and seal the prospective HR-3 block-3 scope-relaxation treatment.

This is a preflight builder only: it hashes the immutable Pilot-1 parent without
loading it, imports no model implementation, creates no optimizer, and never
opens a FINAL or sacred artifact.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import stat
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(r"C:\DaveLM-CADAVER")
OUT = ROOT / "human_readiness_hr3_block3_causal_seed87006_v1"
SOURCE = ROOT / "human_readiness_hr1_causal_aligned_seed87006_v1"
READINESS = ROOT / "human_test_readiness_v2_seed87010"
PARENT = ROOT / "language_pilot_1_early_block_protection_seed8380" / "pilot_run" / "checkpoints" / "seed_8380" / "latest.pt"
TOKENIZER = Path(r"C:\DaveLM-v0.9\tokenizer\v0_7\davelm_tokenizer.json")
PARENT_SHA = "2281d20ebd3ae9c5c7bdf8af92518e6ca50a9d777f6b336fb89891932a2a12cb"
TOKENIZER_SHA = "e1c18bae74f6d502c0012953b3eef63f787cefd41c9a47b94e803e665dab343b"


def sha(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def write_text(path: Path, text: str) -> None:
    path.write_text(text.replace("\r\n", "\n"), encoding="utf-8", newline="\n")


def write_json(path: Path, value: Any) -> None:
    write_text(path, json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n")


def payload_manifest(path: Path) -> list[dict[str, Any]]:
    excluded = {"SHA256SUMS.txt", "FREEZE_RECEIPT.json", "FREEZE_RECEIPT.sha256"}
    files = sorted(p for p in path.rglob("*") if p.is_file() and p.name not in excluded)
    return [{"path": p.relative_to(path).as_posix(), "sha256": sha(p), "bytes": p.stat().st_size} for p in files]


def verify_source_bundle(path: Path, expected_status: str) -> dict[str, Any]:
    receipt_path = path / "FREEZE_RECEIPT.json"
    expected = (path / "FREEZE_RECEIPT.sha256").read_text(encoding="utf-8").strip().split()[0]
    assert sha(receipt_path) == expected
    receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
    assert receipt["status"] == expected_status
    assert sha(path / "MANIFEST.json") == receipt["manifest_sha256"]
    assert sha(path / "SHA256SUMS.txt") == receipt["sha256sums_sha256"]
    for line in (path / "SHA256SUMS.txt").read_text(encoding="utf-8").splitlines():
        if line.strip():
            digest, rel = line.split("  ", 1)
            assert sha(path / rel) == digest
    return receipt


def set_readonly(path: Path) -> None:
    for target in path.rglob("*"):
        if target.is_file():
            target.chmod(target.stat().st_mode & ~stat.S_IWRITE)


def main() -> None:
    if OUT.exists():
        raise RuntimeError(f"refusing to overwrite existing HR-3 bundle: {OUT}")
    source_receipt = verify_source_bundle(SOURCE, "CAUSAL_ALIGNMENT_PREFLIGHT_PASS_NO_TRAINING")
    readiness_receipt = verify_source_bundle(READINESS, "FROZEN_PROSPECTIVE_READINESS_DEV_V2")
    assert sha(PARENT) == PARENT_SHA
    assert sha(TOKENIZER) == TOKENIZER_SHA
    OUT.mkdir(parents=True)
    (OUT / "data").mkdir()
    (OUT / "sources").mkdir()

    # Copy the exact corrected-alignment data and literal schedules.  No data,
    # sampling, cadence, or split is regenerated by HR-3.
    copied_data = [
        "ENGLISH_TRAIN.jsonl", "ENGLISH_DEV.jsonl", "ENGLISH_SCHEDULE.json", "BINDING_SCHEDULE.json",
        "binding_rehearsal.json", "binding_dev_pilot0.json", "binding_dev_pilot1.json",
        "CORPUS_MANIFEST.json", "PILOT1_MATERIAL_MANIFEST.json", "PILOT1_TRAINING_SPEC.json",
    ]
    for name in copied_data:
        shutil.copy2(SOURCE / "data" / name, OUT / "data" / name)
    source_map = {
        ROOT / "hr3_block3_runtime.py": OUT / "sources" / "hr3_block3_runtime.py",
        ROOT / "hr3_block3_train.py": OUT / "sources" / "TRAIN_HR3.py",
        ROOT / "hr3_block3_evaluate.py": OUT / "sources" / "EVALUATE_HR3.py",
        ROOT / "validate_hr3_block3_preflight.py": OUT / "sources" / "PREFLIGHT_VALIDATOR.py",
        SOURCE / "sources" / "PINNED_PILOT1_BINDING_IMPLEMENTATION.py": OUT / "sources" / "PINNED_PILOT1_BINDING_IMPLEMENTATION.py",
        SOURCE / "sources" / "treatment13_model.py": OUT / "sources" / "treatment13_model.py",
        SOURCE / "sources" / "CAUSAL_ALIGNED_TRAIN_REAL.py": OUT / "sources" / "CAUSAL_ALIGNED_TRAIN_REFERENCE.py",
    }
    for origin, destination in source_map.items():
        assert origin.exists(), origin
        shutil.copy2(origin, destination)

    payload_hashes = {str((OUT / "data" / name).relative_to(OUT).as_posix()): sha(OUT / "data" / name) for name in copied_data}
    payload_hashes.update({destination.relative_to(OUT).as_posix(): sha(destination) for destination in source_map.values()})
    protocol = {
        "status": "HR3_BLOCK3_PROSPECTIVE_PROTOCOL",
        "version": "HR-3-block3-causal-v1",
        "hypothesis": "Allowing exactly transformer block 3 to adapt during English updates may improve contextual-language acquisition relative to the corrected aligned HR-1 protected scope, while binding rehearsal protects established T13 behavior.",
        "scientific_delta_from_corrected_aligned_hr1": "English updates newly train block 3. Blocks 0-2 remain frozen; all other data, objective, schedule, optimizer, cadence, runtime, binding rehearsal, and gates are byte-for-byte inherited.",
        "parent_path": str(PARENT),
        "parent_sha256": PARENT_SHA,
        "parent_rationale": "Pilot 1 is the only defensible language parent: it has direct language-acquisition evidence and passed both nonsacred binding pools. The aligned HR-1 descendant is an evaluation baseline, not a parent, because it did not meet contextual behavior criteria.",
        "tokenizer_path": str(TOKENIZER),
        "tokenizer_sha256": TOKENIZER_SHA,
        "data": {
            "english_train": "data/ENGLISH_TRAIN.jsonl",
            "english_dev": "data/ENGLISH_DEV.jsonl",
            "english_schedule": "data/ENGLISH_SCHEDULE.json",
            "binding_schedule": "data/BINDING_SCHEDULE.json",
            "binding_rehearsal": "data/binding_rehearsal.json",
            "binding_dev_pools": {"pilot0": "data/binding_dev_pilot0.json", "pilot1": "data/binding_dev_pilot1.json"},
        },
        "training": {
            "seed": 87006,
            "updates": 500,
            "english_updates": 450,
            "binding_updates": 50,
            "cadence": "50 cycles of nine literal English updates followed by one literal binding update",
            "english_batch_size": 64,
            "binding_batch_size": 32,
            "english_scope": "train token embeddings, positional embeddings, transformer blocks 3-7, final normalization, language head; freeze transformer blocks 0-2 and specialized localizer/retrieval parameters",
            "binding_scope": "full established T13 trainable scope restored every tenth update",
            "objective": {
                "english": "z=[BOS=2]+content+[EOS=3]; x=z[:-1], y=z[1:] at the same positions; mean full-vocabulary CE over every content target and final EOS, padded labels=-100",
                "binding": "exact pinned Pilot-1 answer causal CE + LAM 1.0536573711078283 times hard-min permutation-invariant localization loss",
            },
            "optimizer": {"type": "AdamW", "lr": 5e-5, "betas": [0.9, 0.999], "eps": 1e-8, "weight_decay": 0.05, "amsgrad": False, "foreach": False, "fused": False, "scheduler": None, "state": "one fresh optimizer persists continuously across all 500 updates"},
            "gradient_clip_norm": 2.0,
            "runtime": {"python": "3.12", "torch": "2.12.0+rocm7.14.0", "tokenizers": "0.23.1", "device": "cuda", "float32": True, "autocast": False, "tf32": False, "deterministic_algorithms": True, "num_workers": 0, "data_loader_shuffle": False},
        },
        "evaluation": {
            "training_diagnostics_at_updates": [0, 100, 250, 500],
            "readiness_dev": "frozen prospective v2 only; FINAL is sealed and never opened",
            "binding_each_pool": "answer >=76/80; BOTH_DISTINCT >=76/80; slot collapse = 0 independently on both pools",
            "readiness_machine_gates": {"aligned_tinystories_loss_max": 3.25, "fact_correct_min": "20/24", "fact_reversal_pairs_min": "10/12", "fact_complete_families_min": "4/6", "fact_greedy_exact_min": "18/24", "instruction_correct_min": "10/12", "instruction_greedy_exact_min": "9/12", "continuity_correct_min": "10/12", "continuity_greedy_exact_min": "9/12", "generation_non_immediate_eos_min": "16/20", "generation_automatic_non_degenerate_min": "16/20"},
            "human_review_gates": "two blinded reviewers must independently mark at least 14/20 complete, 14/20 relevant, and 12/20 both complete and relevant; disagreement fails the affected item. Raw outputs are retained; human review is required before a HUMAN_TEST_READY claim.",
            "checkpoint_selection": "earliest among updates 100, 250, 500 that passes all frozen machine readiness and binding gates; final readiness eligibility additionally requires the frozen blinded review. No post-hoc selection.",
        },
        "stopping": {"stop_on_binding_failure": True, "stop_on_integrity_or_provenance_failure": True, "no_final_access": True, "no_sacred_access": True, "no_adaptive_hyperparameter_or_scope_change": True, "if_no_checkpoint_passes": "preserve and classify as failed bounded scope treatment; diagnose before another treatment"},
        "readiness_dev": {"path": str(READINESS), "receipt_sha256": sha(READINESS / "FREEZE_RECEIPT.json"), "receipt_status": readiness_receipt["status"], "final_accessed_during_construction": False},
        "source_predecessor": {"path": str(SOURCE), "receipt_sha256": sha(SOURCE / "FREEZE_RECEIPT.json"), "receipt_status": source_receipt["status"]},
        "frozen_payload_hashes": payload_hashes,
        "preflight_constraints": {"checkpoint_loaded": False, "optimizer_created": False, "optimizer_updates": 0, "final_accessed": False, "sacred_accessed": False},
    }
    write_json(OUT / "HR3_PROTOCOL.json", protocol)
    report = """# HR-3 block-3 causal scope-relaxation preflight

HR-3 tests one hypothesis only: Pilot 1's early-block freeze may have limited language/context adaptation. During English updates it releases exactly transformer block 3 while retaining protection of blocks 0--2 and all specialized T13 localizer/retrieval parameters. Binding updates restore the established full T13 scope. The parent, data, literal schedules, objective, optimizer, cadence, runtime, binding rehearsal, and preservation requirements are unchanged from corrected aligned HR-1.

The prospective readiness DEV reference is `human_test_readiness_v2_seed87010`, independently frozen before HR-3 construction. FINAL and sacred material were not opened or enumerated. The treatment is evaluated only on nonsacred DEV and two frozen nonsacred binding pools.

Successful language improvement requires the v2 frozen machine gates and subsequent blinded generation review, while both binding pools independently retain answer >=76/80, BOTH_DISTINCT >=76/80, and zero collapse. A language-only loss reduction cannot pass the treatment.
"""
    write_text(OUT / "PREFLIGHT_REPORT.md", report)
    shutil.copy2(Path(__file__), OUT / "BUILD_HR3_BLOCK3.py")

    subprocess.run([sys.executable, str(OUT / "sources" / "PREFLIGHT_VALIDATOR.py"), "--bundle", str(OUT)], check=True)
    manifest = {"bundle": OUT.name, "payload": payload_manifest(OUT)}
    write_json(OUT / "MANIFEST.json", manifest)
    sums = payload_manifest(OUT)
    write_text(OUT / "SHA256SUMS.txt", "".join(f"{item['sha256']}  {item['path']}\n" for item in sums))
    receipt = {
        "status": "HR3_BLOCK3_PREFLIGHT_PASS",
        "bundle": str(OUT),
        "scientific_specification_unchanged_from": str(SOURCE),
        "scientific_delta": "English scope expands from blocks 4-7 to blocks 3-7 only.",
        "manifest_sha256": sha(OUT / "MANIFEST.json"),
        "sha256sums_sha256": sha(OUT / "SHA256SUMS.txt"),
        "protocol_sha256": sha(OUT / "HR3_PROTOCOL.json"),
        "parent_sha256": PARENT_SHA,
        "tokenizer_sha256": TOKENIZER_SHA,
        "readiness_dev_receipt_sha256": sha(READINESS / "FREEZE_RECEIPT.json"),
        "checkpoint_loaded": False,
        "optimizer_created": False,
        "optimizer_updates": 0,
        "final_accessed": False,
        "sacred_accessed": False,
    }
    write_json(OUT / "FREEZE_RECEIPT.json", receipt)
    write_text(OUT / "FREEZE_RECEIPT.sha256", sha(OUT / "FREEZE_RECEIPT.json") + "  FREEZE_RECEIPT.json\n")
    set_readonly(OUT)
    print(json.dumps({"status": receipt["status"], "bundle": str(OUT), "receipt_sha256": sha(OUT / "FREEZE_RECEIPT.json")}, indent=2))


if __name__ == "__main__":
    main()
