"""T31 native source-to-token copy bridge.

One architectural change relative to T30/T24 lineage: a four-parameter,
zero-initialized ordered copy-logit gate adds logits derived from the
pointer-weighted candidate source token sequence directly to the native
vocabulary logits at answer positions. The ordinary LM path remains intact.
"""
from __future__ import annotations
import torch
import torch.nn as nn
import torch.nn.functional as F
from baby_vnext.binding import BabyVNextWithBinding

class T31CopyModel(BabyVNextWithBinding):
    def __init__(self, config):
        super().__init__(config)
        self.copy_gate = nn.Parameter(torch.zeros(4))

    @staticmethod
    def pointer_route(hidden: torch.Tensor, spans: list[list[int]], query_pos: int):
        q = F.normalize(hidden[0, query_pos], dim=-1)
        keys = []
        for span in spans:
            idx = torch.tensor(span, device=hidden.device, dtype=torch.long)
            keys.append(F.normalize(hidden[0, idx].mean(0), dim=-1))
        key = torch.stack(keys)
        sims = (key * q.unsqueeze(0)).sum(-1)
        weights = F.softmax(sims, dim=-1)
        retrieved = (weights.unsqueeze(-1) * key).sum(0)
        return sims, weights, retrieved

    def copy_probs_for_row(self, row, weights, device, vocab_size):
        """Ordered source-token distribution in answer-context tokenization.

        Candidate token IDs are generated by the frozen tokenizer in the
        answer context (leading-space name + period). They are the mechanical
        lexical realization of each retrieved source identity; no correct label
        is used. Pointer weights select between the two source mentions.
        """
        candidates = [[int(t) for t in c] for c in row["candidate_token_ids"]]
        max_len = max(len(c) for c in candidates)
        out = torch.zeros((max_len, vocab_size), device=device, dtype=weights.dtype)
        for ci, toks in enumerate(candidates):
            w = weights[ci]
            for pos, tok in enumerate(toks):
                out[pos, tok] = out[pos, tok] + w
        return out

    def logits_with_copy(self, hidden, copy_probs, answer_start):
        if hidden.ndim != 3 or copy_probs.ndim != 2:
            raise ValueError("hidden [B,T,D], copy_probs [K,V]")
        logits = self.base_model.language_head(hidden)
        if copy_probs.shape[1] != logits.shape[-1]:
            raise ValueError("copy vocab mismatch")
        steps = min(copy_probs.shape[0], logits.shape[1] - answer_start, self.copy_gate.numel())
        if steps <= 0:
            return logits
        # Centered log copy evidence is a direct vocabulary-logit path. Gate=0
        # is exactly neutral; the ordinary language logits remain available.
        cp = torch.log(copy_probs.clamp_min(1e-9))
        cp = cp - cp.mean(dim=-1, keepdim=True)
        for j in range(steps):
            logits[:, answer_start + j, :] = logits[:, answer_start + j, :] + self.copy_gate[j] * cp[j]
        return logits

    def route_logits_for_row(self, hidden, row, spans, prompt_len, answer_start):
        sims, weights, retrieved = self.pointer_route(hidden, spans, prompt_len - 1)
        cp = self.copy_probs_for_row(row, weights, hidden.device, self.base_model.config.vocab_size)
        logits = self.logits_with_copy(hidden, cp, answer_start)
        return logits, sims, weights, retrieved, cp
